language: python
services: sqlite

install:
    - pip install --upgrade pip
    - python setup.py install
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt

script: py.test tests/
