language: python
services: sqlite

env:
  global:
    - secure: NrStLF2FOw93elOvkQ/q3OEtCIuHBAuFNf47ga5QAOD282ynRguBUhjGz/mEQr/m0AoYpP34qS2x8vci+u1ldU2b4iWQwlqE/Wj3YTAFJl3hZoH4ue7WfFIt2+b5TBtNOGKLHEQ6BOs7Xz5pSdj4izUwFsNc7/G6+rgPS6c5xOOEhak0xYo4LxZCc90XeFWWV4W+778Ugq0VgJFXNpxHHUuuVcNugtDNwfrJxdyDMLHEhNa+o9VP87+vmhkP/BxrWNZJQAibWOtMviWbYvQXxU4kpy7VCVejqpvE6BhYUnKf+TPXHLD89Uckekjz7VagS7Myv++DrB38v0HMPNn8WjtK1y2HdgtcCplYWpgFUzviZ6RyGDHO2jweBsEDjjlHOhK7dHFcU48w63Y8U9FOjiya7RrjZyPpjBfcp2BnSR6il7kKDB14m/7CaGrl7gqIGwcoiD3AIQY2KX4tGd5avYeGAsdsEECJa7wwjjJw6H+NFuIPDhgbEziZP3pDdiOiTpmjbFomdMQaA1CVZl6klHT1tv/C9Em7obYE/gfoE8PCMI7dIGSbvfZnAwsmbReLtvw/GXuRCkzOKo/jjp1U0YYs47R0VDwTJTaYqiP4ISU3bjCnkrC9yDlsqKXs9jcsu6hiQGl4gNUJGlwhpDp9nrs/xT07IWTG2CaVKqO7zro=
    - secure: VIp43odR/3L4DnrZOsKFVPlCiLMF+SzPuovZQW9dZBy8Drkg0JlQQpPmko3nMfoZxTBQIEGGmG2yMRP6WgfyZlbiWYuc37R7AihMX4lqs6mv/VZMYR+9xsqA4evJVNdKHMAb8PuSpNktRg42DiXQum4N1D3rTGNlTEabmoYV0l0Nqmy4UVHg7jDQywuCvD6j1FKZDuT6UtPMAArainWGuMwbNW24lY8MSUlQS5YLQBu9wqxyJR6zZ9FhJOS/2QTm1WR+CtyfgqCqA1MOplAeBRuJQCT//mtk8qh5BDXXVBSSG9LgQmXMkPbbs9fTLzljbLaYZXONTcE+3oSI+hrRtGDzMh7gKpmSmlCbh+Uh1Es8aC5+zLhms/dTRF8yTFhGAPcU+fItSwTIMgF7Npfx/fYvhRBNZY/b/5vFuAGYyBlvFiZZqVxBTCv9MEsVrLru5jbcjKhb0eJ5C/Uo/6T4ii4tUjtBlJWYqK4v1qe3iqEpp3KaMAF4u4e8XTuMkxxZpmkO02TGtF+z5Mhv2/TzEYFsn1IYAunt6hIXUI1EuA38UitXiav6lOwSvSmH/vLfDYs8z4Flma/GJNwkxU3YXaf1FTh1eQnNpPklYFtH1P/+2qS5kgw/nK5DpTfqfXu3mgrYD19z4nbTA1hqd98p040ZME5GBWH2UX6/k9WeRWE=

addons:
  sauce_connect: true

before_install:
  - pip install codecov
  - python tests/manage.py collectstatic

after_success:
  - codecov

install:
    - pip install --upgrade pip
    - python setup.py install
    - pip install -r tests/requirements.txt

script: py.test --cov=djpressor/ --cov-config=.coveragerc
