language: python
services: sqlite

addons:
  sauce_connect:
    username: "FundedByMe"
    access_key:
        secure: "siyIYOl43qAXZ9pV/ECZT0rI6UUC+D9nHz1XiRmIxQ6pMbOxzkqsfKm5ntV6PdN/HmQxiSX+YRpRzXAE4+O/3NLHzKwaagnOpwz26syB5t1BiA9mn/V5yEJ395PQyE6rgwrFuDCTOSIqwodW6rp1PKCabbBkS1W7XHfqb0iQBLjXrpUepmzeIiLCOwbgvY908cXfkXZgAqhPylx21v+RDPjAqKo35gkps+Z62YM5oDqc77AukFGss2kh3SDXeMtnX6gpWmDLOy7UmIc4EzdAelwlx2teID8Kz2ESD94uhpfNCDMs4bKnDWIWbtHov88//FZzDqfsGMlwN0cMaYy+ClaixRJFLyVUfn0GWVgrpdnjxkEy9dmLbVJU44xz351wyC5WI75AJqn4Wy2ZNYMjSzj9Xu8f+Vh/rMg5Bhog2sujcl6DLDqYm6Pl9GmNdkPhwi29g+yexJ2FwMsPfK1ElJi88y+lIRM5B7kXAWE/dN/LfJuhYxzHwNQjVZSt5x/PBALexDvn2UkqllRLz0JFg8xukOYDSzwpKKsrQ7enq0xgYm25B9oZm8mBJfGC3+TS8xE7IKs0JuGGv8tkdoACu3nVrdPxzHUu9KkYiWgfj/eOkj72RYkYtGw+YJQJwOWHnB0E2GS5oFP+2adcZYlDuHA2hydYoOKr77m+Ox16SQw="

install:
    - pip install --upgrade pip
    - python setup.py install
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt

script: py.test tests/
